# 

version: 2

############################
# 1. RAW SOURCE DECLARATION
############################
sources:
  - name: telecom_raw
    schema: raw_schema
    database: your_redshift_database   # optional
    tables:

      - name: call_logs
        description: "Raw call logs extracted from S3"
        columns:
          - name: call_id
            tests: [not_null, unique]
          - name: customer_id
            tests: [not_null]
          - name: complaint_category
          - name: agent_id
          - name: call_start_time
          - name: call_end_time
          - name: resolutionstatus
          - name: calllogsgenerationdate
          - name: load_timestamp        

      - name: social_media
        description: "Raw social media complaints (JSON)"
        columns:
          - name: complaint_id
            tests: [not_null, unique]
          - name: customer_id
            tests: [not_null]
          - name: complaint_category
          - name: agent_id
          - name: resolutionstatus
          - name: request_date
          - name: resolution_date
          - name: media_channel
          - name: mediacomplaintgenerationdate
          - name: load_timestamp

      - name: webforms
        description: "Raw web form complaints from Postgres"
        columns:
          - name: request_id
            tests: [not_null, unique]
          - name: customer_id
            tests: [not_null]
          - name: complaint_category
          - name: agent_id
          - name: resolutionstatus
          - name: request_date
          - name: resolution_date
          - name: webformgenerationdate
          - name: load_timestamp

      - name: customers
        description: "Raw customer master data"
        columns:
          - name: customer_id
            tests: [not_null, unique]
          - name: name
          - name: gender
            tests:
              - accepted_values:
                  values: ['Male', 'Female', 'Unknown']
          - name: date_of_birth
          - name: signup_date
          - name: email
          - name: address
          - name: load_timestamp

      - name: agents
        description: "Raw agent master data"
        columns:
          - name: id
            tests: [not_null, unique]
          - name: name
          - name: experience
          - name: state
          - name: load_timestamp


############################
# 2. STAGING MODELS
############################

models:
  - name: stg_call_logs
    description: "Cleaned and standardized call log data"
    columns:
      - name: call_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: agent_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_agents')
              field: agent_id
      - name: resolutionstatus
        tests:
          - accepted_values:
              values: ['resolved', 'pending', 'unresolved']

  - name: stg_social_media
    description: "Cleaned and standardized social media complaints"
    columns:
      - name: complaint_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: agent_id
        tests:
          - relationships:
              to: ref('stg_agents')
              field: agent_id

  - name: stg_webforms
    description: "Cleaned and standardized webform complaints"
    columns:
      - name: request_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: agent_id
        tests:
          - relationships:
              to: ref('stg_agents')
              field: agent_id

  - name: stg_customers
    description: "Standardized customer table"
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: stg_agents
    description: "Standardized agent master table"
    columns:
      - name: agent_id
        tests: [not_null, unique]


############################
# 3. MARTS (FACTS & DIMENSIONS)
############################

# DIM CUSTOMERS
  - name: dim_customers
    description: "Customer dimension containing demographic and profile data"
    columns:
      - name: customer_id
        tests: [not_null, unique]

# DIM AGENTS
  - name: dim_agents
    description: "Agent dimension table"
    columns:
      - name: agent_id
        tests: [not_null, unique]


# FACT COMPLAINTS (Unified from call, social, webform)
  - name: fact_complaints
    description: "Unified fact table of all customer complaints across every channel"
    columns:
      - name: complaint_id
        tests: [unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: agent_id
        tests:
          - relationships:
              to: ref('dim_agents')
              field: agent_id
      - name: channel
        tests:
          - accepted_values:
              values: ['call', 'social', 'webform']
      - name: resolutionstatus
        tests:
          - accepted_values:
              values: ['resolved', 'pending', 'unresolved']

