# 

version: 2

############################
# 1. RAW SOURCE DECLARATION
############################
sources:
  - name: telecom_data
    schema: test_raw_schema
    tables:
      - name: call_logs
      - name: customers
      - name: webforms
      - name: social_media
      - name: agents


############################
# 2. STAGING MODELS
############################

models:
  - name: stg_call_logs
    description: "Cleaned and standardized call log data"
    columns:
      - name: call_id
        tests: [not_null]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: agent_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_agents')
              field: agent_id
      - name: resolutionstatus
        tests:
          - accepted_values:
              values: ['resolved', 'pending', 'unresolved']

  - name: stg_socialmedias
    description: "Cleaned and standardized social media complaints"
    columns:
      - name: complaint_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: agent_id
        tests:
          - relationships:
              to: ref('stg_agents')
              field: agent_id

  - name: stg_webforms
    description: "Cleaned and standardized webform complaints"
    columns:
      - name: request_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: agent_id
        tests:
          - relationships:
              to: ref('stg_agents')
              field: agent_id

  - name: stg_customers
    description: "Standardized customer table"
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: stg_agents
    description: "Standardized agent master table"
    columns:
      - name: agent_id
        tests: [not_null, unique]


############################
# 3. MARTS (FACTS & DIMENSIONS)
############################

# DIM CUSTOMERS
  - name: dim_customers
    description: "Customer dimension containing demographic and profile data"
    columns:
      - name: customer_id
        tests: [not_null, unique]

# DIM AGENTS
  - name: dim_agents
    description: "Agent dimension table"
    columns:
      - name: agent_id
        tests: [not_null, unique]


# FACT COMPLAINTS (Unified from call, social, webform)
  - name: fact_complaints
    description: "Unified fact table of all customer complaints across every channel"
    columns:
      - name: complaint_id
        tests: [unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: agent_id
        tests:
          - relationships:
              to: ref('dim_agents')
              field: agent_id
      - name: channel
        tests:
          - accepted_values:
              values: ['call', 'social', 'webform']
      - name: resolutionstatus
        tests:
          - accepted_values:
              values: ['resolved', 'pending', 'unresolved']

